[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "freetype",
  "harfbuzz",
  "expat",
  "fontconfig",
  "dbus",
  "at-spi2-core",
  "cups",
  "libdrm",
  "mesa",
  "libxkbcommon",
  "pango",
  "cairo",
  "glib",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "alsa-lib",
  "gtk3",
  "udev",
  "libuuid"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx playwright install chromium"]

[start]
cmd = "node index.js"
